<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>spt-reflection</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Assembly-CSharp" HintPath="..\Shared\Hollowed\hollowed.dll" Private="False" />
    <Reference
      Include="bsg.componentace.compression.libs.zlib"
      HintPath="..\Shared\Managed\bsg.componentace.compression.libs.zlib.dll"
      Private="False"
    />
    <Reference Include="Comfort" HintPath="..\Shared\Managed\Comfort.dll" Private="False" />
    <Reference Include="FilesChecker" HintPath="..\Shared\Managed\FilesChecker.dll" Private="False" />
    <Reference Include="UnityEngine" HintPath="..\Shared\Managed\UnityEngine.dll" Private="False" />
    <Reference Include="UnityEngine.CoreModule" HintPath="..\Shared\Managed\UnityEngine.CoreModule.dll" Private="False" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference
      Include="BepInEx.Analyzers"
      PrivateAssets="All"
      IncludeAssets="runtime; build; native; contentfiles; analyzers; buildtransitive"
    />
    <PackageReference Include="BepInEx.Core" />
    <PackageReference Include="BepInEx.PluginInfoProps" />
    <PackageReference Include="Newtonsoft.Json" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SPT.Common\SPT.Common.csproj" />
  </ItemGroup>
</Project>
