<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>spt-prepatch</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Assembly-CSharp" HintPath="..\Shared\Hollowed\hollowed.dll" Private="False" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SPT.Common\SPT.Common.csproj" />
    <ProjectReference Include="..\SPT.Reflection\SPT.Reflection.csproj" />
  </ItemGroup>
</Project>
