<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\SPT.Common\SPT.Common.csproj" />
    <ProjectReference Include="..\SPT.Core\SPT.Core.csproj" />
    <ProjectReference Include="..\SPT.Reflection\SPT.Reflection.csproj" />
    <ProjectReference Include="..\SPT.PrePatch\SPT.PrePatch.csproj" />
    <ProjectReference Include="..\SPT.Debugging\SPT.Debugging.csproj" />
    <ProjectReference Include="..\SPT.SinglePlayer\SPT.SinglePlayer.csproj" />
    <ProjectReference Include="..\SPT.Custom\SPT.Custom.csproj" />
  </ItemGroup>
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="pwsh -NoProfile -ExecutionPolicy Bypass ../build.ps1" WorkingDirectory="$(ProjectDir)" />
  </Target>
</Project>
