<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" />
    <PackageVersion Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageVersion Include="BepInEx.Core" Version="5.4.21" />
    <PackageVersion Include="BepInEx.Analyzers" Version="1.0.8" />
    <PackageVersion Include="BepInEx.PluginInfoProps" Version="2.1.0" />
  </ItemGroup>
</Project>
