<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>spt-custom</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="AnimationSystem.Types" HintPath="..\Shared\Managed\AnimationSystem.Types.dll" Private="False" />
    <Reference Include="Assembly-CSharp" HintPath="..\Shared\Hollowed\hollowed.dll" Private="False" />
    <Reference Include="Comfort" HintPath="..\Shared\Managed\Comfort.dll" Private="False" />
    <Reference Include="DissonanceVoip" HintPath="..\Shared\Managed\DissonanceVoip.dll" Private="False" />
    <Reference Include="Sirenix.Serialization" HintPath="..\Shared\Managed\Sirenix.Serialization.dll" Private="False" />
    <Reference Include="Unity.TextMeshPro" HintPath="..\Shared\Managed\Unity.TextMeshPro.dll" Private="False" />
    <Reference Include="UnityEngine" HintPath="..\Shared\Managed\UnityEngine.dll" Private="False" />
    <Reference Include="UnityEngine.AIModule" HintPath="..\Shared\Managed\UnityEngine.AIModule.dll" Private="False" />
    <Reference Include="UnityEngine.AnimationModule" HintPath="..\Shared\Managed\UnityEngine.AnimationModule.dll" Private="False" />
    <Reference Include="UnityEngine.AssetBundleModule" HintPath="..\Shared\Managed\UnityEngine.AssetBundleModule.dll" Private="False" />
    <Reference Include="UnityEngine.AudioModule" HintPath="..\Shared\Managed\UnityEngine.AudioModule.dll" Private="False" />
    <Reference Include="UnityEngine.CoreModule" HintPath="..\Shared\Managed\UnityEngine.CoreModule.dll" Private="False" />
    <Reference Include="UnityEngine.IMGUIModule" HintPath="..\Shared\Managed\UnityEngine.IMGUIModule.dll" Private="False" />
    <Reference
      Include="UnityEngine.ParticleSystemModule"
      HintPath="..\Shared\Managed\UnityEngine.ParticleSystemModule.dll"
      Private="False"
    />
    <Reference Include="UnityEngine.PhysicsModule" HintPath="..\Shared\Managed\UnityEngine.PhysicsModule.dll" Private="False" />
    <Reference Include="UnityEngine.TerrainModule" HintPath="..\Shared\Managed\UnityEngine.TerrainModule.dll" Private="False" />
    <Reference
      Include="UnityEngine.TerrainPhysicsModule"
      HintPath="..\Shared\Managed\UnityEngine.TerrainPhysicsModule.dll"
      Private="False"
    />
    <Reference Include="UnityEngine.TextRenderingModule" HintPath="..\Shared\Managed\UnityEngine.TextRenderingModule.dll" Private="False" />
    <Reference Include="UnityEngine.UI" HintPath="..\Shared\Managed\UnityEngine.UI.dll" Private="False" />
    <Reference Include="UnityEngine.UIModule" HintPath="..\Shared\Managed\UnityEngine.UIModule.dll" Private="False" />
    <Reference Include="Unity.ScriptableBuildPipeline" HintPath="..\Shared\Managed\Unity.ScriptableBuildPipeline.dll" Private="False" />
    <Reference
      Include="UnityEngine.ImageConversionModule"
      HintPath="..\Shared\Managed\UnityEngine.ImageConversionModule.dll"
      Private="False"
    />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SPT.Core\SPT.Core.csproj" />
    <ProjectReference Include="..\SPT.PrePatch\SPT.PrePatch.csproj" />
    <ProjectReference Include="..\SPT.Common\SPT.Common.csproj" />
    <ProjectReference Include="..\SPT.Reflection\SPT.Reflection.csproj" />
    <ProjectReference Include="..\SPT.SinglePlayer\SPT.SinglePlayer.csproj" />
  </ItemGroup>
</Project>
