name: Trigger Main Build Pipeline

on:
  push:
    tags:
      - "*"

jobs:
  trigger-main-build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Build Workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.BUILD_REPO_ACCESS_TOKEN }}
          repository: sp-tarkov/build
          event-type: build-trigger
          client-payload: |
            {
              "repository": "${{ github.repository }}",
              "tag": "${{ github.ref_name }}"
            }
